##PSA bug type to parameter references
Buffer Copy without Checking Size of Input=ps-bcis
Divide by Zero=ps-dbz
Free of Memory Not on the Heap=ps-fnhm
Incorrect Calculation of Buffer Size=ps-icb
NULL Pointer Dereference=ps-npd
Use After Free=ps-uaf
Use of Uninitialized Variable=ps-uuv
Bad Buffer Size from System Function=ps-msbo
Return of Stack Address=ps-rsa
Invalid Use of Stack Address=ps-rsa
Memory Leak=ps-ml
Integer Overflow=ps-iow
Double Free=ssu-dbf
File Descriptor Leak=ps-fdl
Taint-Style Vulnerability=ps-taint
Format String Vulnerability=ps-taint
Command Injection Vulnerability=ps-taint
System/Configuration Setting Vulnerability=ps-taint
Path Traversal Vulnerability=ps-taint
Sensitive Data Transmission/Storage Vulnerability=ps-taint
Uncontrolled Memory Allocation Vulnerability=ps-taint
Buffer/Memory Writing Length Manipulation Vulnerability=ps-taint
Process Control Vulnerability=ps-taint
Traps=ps-trap
Data Race=ps-race
Use of Expired File Descriptor=ps-fduac