# 输出结果语言
# 包含: CN, EN
Tool.Language = "CN"

# 日志等级
# 包含: none, error, warning, info, debug, all
Tool.LogLevel = "none"

# 日志文件路径
Tool.LogFile = ""

# 是否检查头文件
Tool.IsCheckHeader = true

# 是否检查系统头文件
Tool.IsCheckSystemHeader = false

# 是否可以通过在上方添加注释的方式，抑制 advisory 类报警
# 影响规则:
# MISRA C:2012 11.4
# MISRA C:2012 20.10
Tool.IsMaskAdvisoryByComment = true

# 分析使用的数据模型
# 包含: llp64, lp64
Global.DataModels = "llp64"

# C++ 标准库标识符列表
# 包含: cpp20
Global.CppStandardIndetifier = "cpp20"

# C 标准库标识符列表
# 包含: c99
Global.CStandardIndetifier = "c99"

# MISRA C:2012 10.* 规则的报错强度
# 包含：strong, weak
EssentialType.level = "weak"