C:\Users\admin\Desktop\HDL\6_2_1_1_12.v
C:\Users\admin\Desktop\HDL\6_2_1_1_15.v
C:\Users\admin\Desktop\HDL\6_2_1_1_18_1.v
C:\Users\admin\Desktop\HDL\6_2_1_1_19_0.v
C:\Users\admin\Desktop\HDL\6_2_1_1_19_1.v
C:\Users\admin\Desktop\HDL\6_2_1_1_20_0.v
C:\Users\admin\Desktop\HDL\6_2_1_1_21_0.v
C:\Users\admin\Desktop\HDL\6_2_1_1_21_1.v
C:\Users\admin\Desktop\HDL\6_2_1_1_23.v
C:\Users\admin\Desktop\HDL\6_2_1_1_24.v
C:\Users\admin\Desktop\HDL\6_2_1_1_25.v
C:\Users\admin\Desktop\HDL\6_2_1_1_31.v
C:\Users\admin\Desktop\HDL\6_2_1_1_32.v
C:\Users\admin\Desktop\HDL\6_2_1_1_33.v
C:\Users\admin\Desktop\HDL\6_2_1_1_34.v
C:\Users\admin\Desktop\HDL\6_2_1_1_35.v
C:\Users\admin\Desktop\HDL\6_2_1_1_4.v
C:\Users\admin\Desktop\HDL\6_2_1_1_5.v
C:\Users\admin\Desktop\HDL\6_2_1_1_6.v
C:\Users\admin\Desktop\HDL\6_2_1_1_7.v
C:\Users\admin\Desktop\HDL\6_2_1_1_8.v
C:\Users\admin\Desktop\HDL\6_2_5_1_2.v
C:\Users\admin\Desktop\HDL\6_2_5_1_3.v
C:\Users\admin\Desktop\HDL\6_2_5_1_5.v
C:\Users\admin\Desktop\HDL\6_2_6_1_1.v
C:\Users\admin\Desktop\HDL\6_2_6_1_2.v
C:\Users\admin\Desktop\HDL\6_2_6_1_3.v
C:\Users\admin\Desktop\HDL\6_2_6_1_4.v
C:\Users\admin\Desktop\HDL\6_2_6_1_5.v
C:\Users\admin\Desktop\HDL\6_2_7_1_1.v
C:\Users\admin\Desktop\HDL\6_2_7_1_2.v
C:\Users\admin\Desktop\HDL\6_2_7_1_3.v
C:\Users\admin\Desktop\HDL\6_2_7_1_4.v
C:\Users\admin\Desktop\HDL\6_2_7_1_5.v
C:\Users\admin\Desktop\HDL\6_2_7_1_6.v
C:\Users\admin\Desktop\HDL\6_2_7_1_7.v
C:\Users\admin\Desktop\HDL\6_2_8_1_1.v
C:\Users\admin\Desktop\HDL\6_2_8_1_2.v
C:\Users\admin\Desktop\HDL\6_2_9_1_1_0.v
C:\Users\admin\Desktop\HDL\6_2_9_1_1_1.v
C:\Users\admin\Desktop\HDL\6_2_9_1_2_1.v
C:\Users\admin\Desktop\HDL\6_2_9_1_2_2.v
C:\Users\admin\Desktop\HDL\6_2_9_1_2_3.v
C:\Users\admin\Desktop\HDL\6_2_9_1_3.v
C:\Users\admin\Desktop\HDL\6_2_9_1_4_0.v
C:\Users\admin\Desktop\HDL\6_2_9_1_4_1.v
C:\Users\admin\Desktop\HDL\6_2_9_1_5_0.v
C:\Users\admin\Desktop\HDL\6_2_9_1_5_1.v
C:\Users\admin\Desktop\HDL\6_2_9_1_6.v
C:\Users\admin\Desktop\HDL\6_3_1_1_0.v
C:\Users\admin\Desktop\HDL\6_3_1_1_1.v
C:\Users\admin\Desktop\HDL\6_3_1_1_2.v
C:\Users\admin\Desktop\HDL\6_3_1_2.v
C:\Users\admin\Desktop\HDL\para.v
C:\Users\admin\Desktop\HDL\R6_2_11_1_7_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_2_1_1_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_2_1_2_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_2_1_3_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_3_1_1_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_3_1_2_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_3_1_3_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_3_1_4_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_3_1_5.vhd
C:\Users\admin\Desktop\HDL\R6_2_4_1_1_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_4_1_2_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_4_1_3.vhd
C:\Users\admin\Desktop\HDL\R6_2_6_1_1_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_6_2.vhd
C:\Users\admin\Desktop\HDL\R6_2_7_1_1_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_8_1_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_8_1_2_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_9_1_1_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_9_1_2_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_9_1_3_0_0.vhd
C:\Users\admin\Desktop\HDL\R6_2_9_1_4.vhd
C:\Users\admin\Desktop\HDL\R6_2_9_1_5.vhd
-f xml
-lang C
-filte 1
-o "D:\SunwiseInfo\SunwiseHDLChecker3.0\workspace4\hdl\out\hdl.xml"
