-t ANSI
-d "__attribute__(X)="
-i "D:\SunwiseInfo\HDLChecker3.2.0\includes\ansi"
-q "D:\SunwiseInfo\HDLChecker3.2.0\includes\ansi"
-s char=8
-s long=16
-s double=16
-s dataptr=8
-s codeptr=8
-s short=16
-s float=16
-s long_double=32
-s int=16
-s long_long=32
