[c]
[1,1]--std=c11

[0,0]--std=c99

[0,0]--std=c89


[cpp]
[1,1]--std=c++11

[0,0]--std=c++03


[ConfParams]
##开启5个线程异步检查
[0,0]-j 5

##输出xml格式报告
[1,1]--xml

##开启的检查项(默认所有)
[1,1]--enable=[all;all;all,style,performance,portability,information,unusedFunction;m]


[unConfParams]
