[c]
##[1,1]-std=c89

##clang 3.1 and later
##[1,1]-std=c11

##[1,1]-std=gnu99

##[0,0]-std=c99

##clang 3.6 and later,if no --std,gnu11 is default
##[0,0]-std=gnu11

##[0,0]-std=c94

##[0,0]-std=gnu89


[cpp]
##[0,0]-std=c++03

##clang 5 and later
##[0,0]-std=c++17

##[0,0]-std=c++0x

##[0,0]-std=gnu++0x

##clang 3.3 and later
##[0,0]-std=c++11

##clang 3.4 and later
##[1,1]-std=c++14

##[0,0]-std=c++98


[ConfParams]


##是否将bc文件链接后再分析,1链接，0不链接
[1,1]link_bc=[1;1;0,1;s]
[1,1]--result=[high;high;high,all;s]
[unConfParams]