[c]
[1,1]-std=c89

##clang 3.1 and later
[1,1]-std=c11

[1,1]-std=gnu99

[0,0]-std=c99

##clang 3.6 and later,if no --std,gnu11 is default
[0,0]-std=gnu11

[0,0]-std=c94

[0,0]-std=gnu89


[cpp]
[0,0]-std=c++03

##clang 5 and later
[0,0]-std=c++17

[0,0]-std=c++0x

[0,0]-std=gnu++0x

##clang 3.3 and later
[0,0]-std=c++11

##clang 3.4 and later
[1,1]-std=c++14

[0,0]-std=c++98


[ConfParams]
##开启所有默认重量级检测，*为默认检测
[0,0]-ps-stable

##启用副作用分析，默认不开启 (增加召回，降低分析速度)
[0,0]-psa-enable-side-effect-source

##开启函数指针解析
[0,0]-falcon-cg

##开启所有默认轻量级检测，*为默认检测
[0,0]-ssu-stable

##用户自定义内存操作函数列表
[0,0]-load-memory-spec=[none;none;str;a]

##用户自定义污点函数列表
[0,0]-load-taint-spec=[none;none;str;a]

##用户自定义IO函数列表
[0,0]-load-io-spec=[none;none;str;a]

##深度漏洞挖掘
[0,0]-execution-mode=[normal;normal;glancing,quick,normal,thorough,digging;s]

##设置函数调用追踪深度 （默认 6）
[0,0]-inline-depth=[6;6;int;s]

##设置每个函数指针可以指向的最大函数数量，默认1（增加召回，降低分析精度，增加误报)）
[0,0]-falcon-restrict-function-pointer-size=[1;1;int;s]

##用户自定义缓冲区访问函数列表
[0,0]-load-buffer-access-spec=[none;none;str;a]

##是否将bc文件链接后再分析,1链接，0不链接
[0,0]link_bc=[0;0;0,1;s]

##CPU使用量
[0,0]-nworkers=[4;4;uint;s]


[unConfParams]
##生成报告格式，默认html，也可是plain-text的纯文本刻度JSON报告
[1]-report-format=text-plain

##在输入的llvm bitcode中没有debug信息的情况下依然执行分析
[1]-omit-no-dbginfo

